package pikefin.hibernate;

// Generated Aug 1, 2012 11:34:38 AM by Hibernate Tools 3.4.0.CR1

/**
 * CountryEntity generated by hbm2java
 */
public class CountryEntity implements java.io.Serializable {

	private Integer countryEntityId;
	private Integer countryId;
	private boolean defaultCountry;

	public CountryEntity() {
	}

	public CountryEntity(Integer countryId, boolean defaultCountry) {
		this.countryId = countryId;
		this.defaultCountry = defaultCountry;
	}

	public Integer getCountryEntityId() {
		return this.countryEntityId;
	}

	public void setCountryEntityId(Integer countryEntityId) {
		this.countryEntityId = countryEntityId;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public boolean isDefaultCountry() {
		return this.defaultCountry;
	}

	public void setDefaultCountry(boolean defaultCountry) {
		this.defaultCountry = defaultCountry;
	}

}
