package pikefin.hibernate;

// Generated Aug 1, 2012 11:34:38 AM by Hibernate Tools 3.4.0.CR1

/**
 * CountryWrapper generated by hbm2java
 */
public class CountryWrapper implements java.io.Serializable {

	private Integer countryEntityId;
	private boolean defaultCountry;
	private Country country;

	public CountryWrapper() {
	}

	public CountryWrapper(Country country) {
		this.country = country;
	}

	public CountryWrapper(boolean defaultCountry, Country country) {
		this.defaultCountry = defaultCountry;
		this.country = country;
	}

	public Integer getCountryEntityId() {
		return this.countryEntityId;
	}

	public void setCountryEntityId(Integer countryEntityId) {
		this.countryEntityId = countryEntityId;
	}

	public boolean isDefaultCountry() {
		return this.defaultCountry;
	}

	public void setDefaultCountry(boolean defaultCountry) {
		this.defaultCountry = defaultCountry;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

}
