package pikefin.hibernate;

// Generated Jun 18, 2012 7:54:36 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Exclude generated by hbm2java
 */
public class Exclude implements java.io.Serializable {

	private Integer excludeId;
	private Integer taskId;
	private Integer beginDay;
	private String beginTime;
	private Integer endDay;
	private String endTime;
	private Integer type;
	private Date oneTimeDate;

	public Exclude() {
	}

	public Exclude(Integer taskId, Integer beginDay, String beginTime,
			Integer endDay, String endTime, Integer type, Date oneTimeDate) {
		this.taskId = taskId;
		this.beginDay = beginDay;
		this.beginTime = beginTime;
		this.endDay = endDay;
		this.endTime = endTime;
		this.type = type;
		this.oneTimeDate = oneTimeDate;
	}

	public Integer getExcludeId() {
		return this.excludeId;
	}

	public void setExcludeId(Integer excludeId) {
		this.excludeId = excludeId;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Integer getBeginDay() {
		return this.beginDay;
	}

	public void setBeginDay(Integer beginDay) {
		this.beginDay = beginDay;
	}

	public String getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public Integer getEndDay() {
		return this.endDay;
	}

	public void setEndDay(Integer endDay) {
		this.endDay = endDay;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Date getOneTimeDate() {
		return this.oneTimeDate;
	}

	public void setOneTimeDate(Date oneTimeDate) {
		this.oneTimeDate = oneTimeDate;
	}

}
