package pikefin.hibernate;

// Generated Aug 1, 2012 11:34:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Entity generated by hbm2java
 */
public class Entity implements java.io.Serializable {

	private Integer entityId;
	private String ticker;
	private String beginFiscalCalendar;
	private Set countryEntities = new HashSet(0);
	private Set countryWrapper = new HashSet(0);

	public Entity() {
	}

	public Entity(String ticker, String beginFiscalCalendar,
			Set countryEntities, Set countryWrapper) {
		this.ticker = ticker;
		this.beginFiscalCalendar = beginFiscalCalendar;
		this.countryEntities = countryEntities;
		this.countryWrapper = countryWrapper;
	}

	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	public String getTicker() {
		return this.ticker;
	}

	public void setTicker(String ticker) {
		this.ticker = ticker;
	}

	public String getBeginFiscalCalendar() {
		return this.beginFiscalCalendar;
	}

	public void setBeginFiscalCalendar(String beginFiscalCalendar) {
		this.beginFiscalCalendar = beginFiscalCalendar;
	}

	public Set getCountryEntities() {
		return this.countryEntities;
	}

	public void setCountryEntities(Set countryEntities) {
		this.countryEntities = countryEntities;
	}

	public Set getCountryWrapper() {
		return this.countryWrapper;
	}

	public void setCountryWrapper(Set countryWrapper) {
		this.countryWrapper = countryWrapper;
	}

}
