package pikefin.hibernate;

// Generated Jun 13, 2012 10:24:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Alert generated by hbm2java
 */
public class Alert implements java.io.Serializable {

	private Integer alertId;
	private float limitValue;
	private Entity alertEntity;
	private TimeEvent alertTimeEvent;
	private Set alertTarget = new HashSet(0);

	public Alert() {
	}

	public Alert(Entity alertEntity, TimeEvent alertTimeEvent) {
		this.alertEntity = alertEntity;
		this.alertTimeEvent = alertTimeEvent;
	}

	public Alert(float limitValue, Entity alertEntity,
			TimeEvent alertTimeEvent, Set alertTarget) {
		this.limitValue = limitValue;
		this.alertEntity = alertEntity;
		this.alertTimeEvent = alertTimeEvent;
		this.alertTarget = alertTarget;
	}

	public Integer getAlertId() {
		return this.alertId;
	}

	public void setAlertId(Integer alertId) {
		this.alertId = alertId;
	}

	public float getLimitValue() {
		return this.limitValue;
	}

	public void setLimitValue(float limitValue) {
		this.limitValue = limitValue;
	}

	public Entity getAlertEntity() {
		return this.alertEntity;
	}

	public void setAlertEntity(Entity alertEntity) {
		this.alertEntity = alertEntity;
	}

	public TimeEvent getAlertTimeEvent() {
		return this.alertTimeEvent;
	}

	public void setAlertTimeEvent(TimeEvent alertTimeEvent) {
		this.alertTimeEvent = alertTimeEvent;
	}

	public Set getAlertTarget() {
		return this.alertTarget;
	}

	public void setAlertTarget(Set alertTarget) {
		this.alertTarget = alertTarget;
	}

}
