package pikefin.hibernate;

// Generated Jun 13, 2012 10:24:38 AM by Hibernate Tools 3.4.0.CR1

/**
 * Job generated by hbm2java
 */
public class Job implements java.io.Serializable {

	private Integer jobId;
	private String dataSet;
	private String urlStatic;
	private boolean tableExtraction;
	private boolean customInsert;

	public Job() {
	}

	public Job(String dataSet, String urlStatic, boolean tableExtraction,
			boolean customInsert) {
		this.dataSet = dataSet;
		this.urlStatic = urlStatic;
		this.tableExtraction = tableExtraction;
		this.customInsert = customInsert;
	}

	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	public String getDataSet() {
		return this.dataSet;
	}

	public void setDataSet(String dataSet) {
		this.dataSet = dataSet;
	}

	public String getUrlStatic() {
		return this.urlStatic;
	}

	public void setUrlStatic(String urlStatic) {
		this.urlStatic = urlStatic;
	}

	public boolean isTableExtraction() {
		return this.tableExtraction;
	}

	public void setTableExtraction(boolean tableExtraction) {
		this.tableExtraction = tableExtraction;
	}

	public boolean isCustomInsert() {
		return this.customInsert;
	}

	public void setCustomInsert(boolean customInsert) {
		this.customInsert = customInsert;
	}

}
