package pikefin.hibernate;

// Generated Jun 13, 2012 10:24:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;

/**
 * LogAlert generated by hbm2java
 */
public class LogAlert implements java.io.Serializable {

	private Integer logAlertId;
	private Calendar dateTimeFired;
	private float diff;
	private boolean emailSent;
	private User logAlertUser;
	private FactData beforeFactData;
	private FactData afterFactData;
	private Entity logAlertEntity;
	private Alert logAlertAlert;

	public LogAlert() {
	}

	public LogAlert(User logAlertUser, FactData beforeFactData,
			FactData afterFactData, Entity logAlertEntity, Alert logAlertAlert) {
		this.logAlertUser = logAlertUser;
		this.beforeFactData = beforeFactData;
		this.afterFactData = afterFactData;
		this.logAlertEntity = logAlertEntity;
		this.logAlertAlert = logAlertAlert;
	}

	public LogAlert(Calendar dateTimeFired, float diff, boolean emailSent,
			User logAlertUser, FactData beforeFactData, FactData afterFactData,
			Entity logAlertEntity, Alert logAlertAlert) {
		this.dateTimeFired = dateTimeFired;
		this.diff = diff;
		this.emailSent = emailSent;
		this.logAlertUser = logAlertUser;
		this.beforeFactData = beforeFactData;
		this.afterFactData = afterFactData;
		this.logAlertEntity = logAlertEntity;
		this.logAlertAlert = logAlertAlert;
	}

	public Integer getLogAlertId() {
		return this.logAlertId;
	}

	public void setLogAlertId(Integer logAlertId) {
		this.logAlertId = logAlertId;
	}

	public Calendar getDateTimeFired() {
		return this.dateTimeFired;
	}

	public void setDateTimeFired(Calendar dateTimeFired) {
		this.dateTimeFired = dateTimeFired;
	}

	public float getDiff() {
		return this.diff;
	}

	public void setDiff(float diff) {
		this.diff = diff;
	}

	public boolean isEmailSent() {
		return this.emailSent;
	}

	public void setEmailSent(boolean emailSent) {
		this.emailSent = emailSent;
	}

	public User getLogAlertUser() {
		return this.logAlertUser;
	}

	public void setLogAlertUser(User logAlertUser) {
		this.logAlertUser = logAlertUser;
	}

	public FactData getBeforeFactData() {
		return this.beforeFactData;
	}

	public void setBeforeFactData(FactData beforeFactData) {
		this.beforeFactData = beforeFactData;
	}

	public FactData getAfterFactData() {
		return this.afterFactData;
	}

	public void setAfterFactData(FactData afterFactData) {
		this.afterFactData = afterFactData;
	}

	public Entity getLogAlertEntity() {
		return this.logAlertEntity;
	}

	public void setLogAlertEntity(Entity logAlertEntity) {
		this.logAlertEntity = logAlertEntity;
	}

	public Alert getLogAlertAlert() {
		return this.logAlertAlert;
	}

	public void setLogAlertAlert(Alert logAlertAlert) {
		this.logAlertAlert = logAlertAlert;
	}

}
