package pikefin.hibernate;

// Generated Jun 18, 2012 7:54:36 AM by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;

/**
 * LogTask generated by hbm2java
 */
public class LogTask implements java.io.Serializable {

	private Integer logTaskId;
	private Integer taskId;
	private Calendar jobProcessStart;
	private Calendar jobProcessEnd;
	private Calendar alertProcessStart;
	private Calendar alertProcessEnd;
	private Integer batch;
	private Integer repeatTypeId;
	private Integer schedule;
	private Calendar stage1Start;
	private Calendar stage1End;
	private Calendar stage2Start;
	private Calendar stage2End;
	private boolean verifyMode;

	public LogTask() {
	}

	public LogTask(Integer taskId, Calendar jobProcessStart,
			Calendar jobProcessEnd, Calendar alertProcessStart,
			Calendar alertProcessEnd, Integer batch, Integer repeatTypeId,
			Integer schedule, Calendar stage1Start, Calendar stage1End,
			Calendar stage2Start, Calendar stage2End, boolean verifyMode) {
		this.taskId = taskId;
		this.jobProcessStart = jobProcessStart;
		this.jobProcessEnd = jobProcessEnd;
		this.alertProcessStart = alertProcessStart;
		this.alertProcessEnd = alertProcessEnd;
		this.batch = batch;
		this.repeatTypeId = repeatTypeId;
		this.schedule = schedule;
		this.stage1Start = stage1Start;
		this.stage1End = stage1End;
		this.stage2Start = stage2Start;
		this.stage2End = stage2End;
		this.verifyMode = verifyMode;
	}

	public Integer getLogTaskId() {
		return this.logTaskId;
	}

	public void setLogTaskId(Integer logTaskId) {
		this.logTaskId = logTaskId;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Calendar getJobProcessStart() {
		return this.jobProcessStart;
	}

	public void setJobProcessStart(Calendar jobProcessStart) {
		this.jobProcessStart = jobProcessStart;
	}

	public Calendar getJobProcessEnd() {
		return this.jobProcessEnd;
	}

	public void setJobProcessEnd(Calendar jobProcessEnd) {
		this.jobProcessEnd = jobProcessEnd;
	}

	public Calendar getAlertProcessStart() {
		return this.alertProcessStart;
	}

	public void setAlertProcessStart(Calendar alertProcessStart) {
		this.alertProcessStart = alertProcessStart;
	}

	public Calendar getAlertProcessEnd() {
		return this.alertProcessEnd;
	}

	public void setAlertProcessEnd(Calendar alertProcessEnd) {
		this.alertProcessEnd = alertProcessEnd;
	}

	public Integer getBatch() {
		return this.batch;
	}

	public void setBatch(Integer batch) {
		this.batch = batch;
	}

	public Integer getRepeatTypeId() {
		return this.repeatTypeId;
	}

	public void setRepeatTypeId(Integer repeatTypeId) {
		this.repeatTypeId = repeatTypeId;
	}

	public Integer getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Integer schedule) {
		this.schedule = schedule;
	}

	public Calendar getStage1Start() {
		return this.stage1Start;
	}

	public void setStage1Start(Calendar stage1Start) {
		this.stage1Start = stage1Start;
	}

	public Calendar getStage1End() {
		return this.stage1End;
	}

	public void setStage1End(Calendar stage1End) {
		this.stage1End = stage1End;
	}

	public Calendar getStage2Start() {
		return this.stage2Start;
	}

	public void setStage2Start(Calendar stage2Start) {
		this.stage2Start = stage2Start;
	}

	public Calendar getStage2End() {
		return this.stage2End;
	}

	public void setStage2End(Calendar stage2End) {
		this.stage2End = stage2End;
	}

	public boolean isVerifyMode() {
		return this.verifyMode;
	}

	public void setVerifyMode(boolean verifyMode) {
		this.verifyMode = verifyMode;
	}

}
