package com.pikefin.businessobjects;

// Generated Jun 18, 2012 7:54:36 AM by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;
import java.util.Date;

/**
 * LogNotification generated by hbm2java
 */
public class LogNotification implements java.io.Serializable {

	private Integer logNotificationId;
	private Integer count;
	private Date processBegin;
	private Date processEnd;
	public Integer getLogNotificationId() {
		return logNotificationId;
	}
	public void setLogNotificationId(Integer logNotificationId) {
		this.logNotificationId = logNotificationId;
	}
	public Integer getCount() {
		return count;
	}
	public void setCount(Integer count) {
		this.count = count;
	}
	public Date getProcessBegin() {
		return processBegin;
	}
	public void setProcessBegin(Date processBegin) {
		this.processBegin = processBegin;
	}
	public Date getProcessEnd() {
		return processEnd;
	}
	public void setProcessEnd(Date processEnd) {
		this.processEnd = processEnd;
	}

	

}
