package com.pikefin.businessobjects;

// Generated Jun 18, 2012 7:54:36 AM by Hibernate Tools 3.4.0.CR1

/**
 * AlertTarget generated by hbm2java
 */
public class AlertTarget implements java.io.Serializable {

	private Integer alertTargetId;
	private String address;
	private Integer type;

	public AlertTarget() {
	}

	public AlertTarget(String address, Integer type) {
		this.address = address;
		this.type = type;
	}

	public Integer getAlertTargetId() {
		return this.alertTargetId;
	}

	public void setAlertTargetId(Integer alertTargetId) {
		this.alertTargetId = alertTargetId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
