package com.pikefin.businessobjects;

// Generated Jun 18, 2012 7:54:36 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EntityGroup generated by hbm2java
 */
public class EntityGroup implements java.io.Serializable {

	private Integer entityGroupId;
	private Set entities = new HashSet(0);

	public EntityGroup() {
	}

	public EntityGroup(Set entities) {
		this.entities = entities;
	}

	public Integer getEntityGroupId() {
		return this.entityGroupId;
	}

	public void setEntityGroupId(Integer entityGroupId) {
		this.entityGroupId = entityGroupId;
	}

	public Set getEntities() {
		return this.entities;
	}

	public void setEntities(Set entities) {
		this.entities = entities;
	}

}
