package com.pikefin.businessobjects;

// Generated Jun 18, 2012 7:54:36 AM by Hibernate Tools 3.4.0.CR1

/**
 * EntityAlias generated by hbm2java
 */
public class EntityAlias implements java.io.Serializable {

	private Integer entityAliasId;
	private String tickerAlias;
	private Entity entity;

	public EntityAlias() {
	}

	public EntityAlias(Entity entity) {
		this.entity = entity;
	}

	public EntityAlias(String tickerAlias, Entity entity) {
		this.tickerAlias = tickerAlias;
		this.entity = entity;
	}

	public Integer getEntityAliasId() {
		return this.entityAliasId;
	}

	public void setEntityAliasId(Integer entityAliasId) {
		this.entityAliasId = entityAliasId;
	}

	public String getTickerAlias() {
		return this.tickerAlias;
	}

	public void setTickerAlias(String tickerAlias) {
		this.tickerAlias = tickerAlias;
	}

	public Entity getEntity() {
		return this.entity;
	}

	public void setEntity(Entity entity) {
		this.entity = entity;
	}

}
