package pikefin.hibernate;

// Generated Jun 13, 2012 10:24:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Entity generated by hbm2java
 */
public class Entity implements java.io.Serializable {

	private Integer entityId;
	private String ticker;
	private Set country = new HashSet(0);

	public Entity() {
	}

	public Entity(String ticker, Set country) {
		this.ticker = ticker;
		this.country = country;
	}

	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	public String getTicker() {
		return this.ticker;
	}

	public void setTicker(String ticker) {
		this.ticker = ticker;
	}

	public Set getCountry() {
		return this.country;
	}

	public void setCountry(Set country) {
		this.country = country;
	}

}
