package pikefin.hibernate;

// Generated Jun 13, 2012 10:24:38 AM by Hibernate Tools 3.4.0.CR1

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private Integer scheduleId;
	private Integer priority;
	private Integer taskId;
	private Integer repeatTypeId;
	private boolean verifyMode;
	private Task task;
	private RepeatType repeatType;

	public Schedule() {
	}

	public Schedule(Task task, RepeatType repeatType) {
		this.task = task;
		this.repeatType = repeatType;
	}

	public Schedule(Integer priority, Integer taskId, Integer repeatTypeId,
			boolean verifyMode, Task task, RepeatType repeatType) {
		this.priority = priority;
		this.taskId = taskId;
		this.repeatTypeId = repeatTypeId;
		this.verifyMode = verifyMode;
		this.task = task;
		this.repeatType = repeatType;
	}

	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Integer getRepeatTypeId() {
		return this.repeatTypeId;
	}

	public void setRepeatTypeId(Integer repeatTypeId) {
		this.repeatTypeId = repeatTypeId;
	}

	public boolean isVerifyMode() {
		return this.verifyMode;
	}

	public void setVerifyMode(boolean verifyMode) {
		this.verifyMode = verifyMode;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public RepeatType getRepeatType() {
		return this.repeatType;
	}

	public void setRepeatType(RepeatType repeatType) {
		this.repeatType = repeatType;
	}

}
