package com.pikefin;

public enum ErrorCode {
	COULD_NOT_SAVE_ALERT_DATA,
	COULD_NOT_UPDATE_ALERT_DATA,
	COULD_NOT_LOAD_ALERT_DATA_WITH_ID,
	COULD_NOT_DELETE_ALERT_INFORMATION,
	COULD_NOT_SAVE_COUNTRY_DATA,
	COULD_NOT_UPDATE_COUNTRY_DATA,
	COULD_NOT_LOAD_COUNTRY_DATA_WITH_ID,
	COULD_NOT_DELETE_COUNTRY_INFORMATION,
COULD_NOT_SAVE_USER_DATA,
COULD_NOT_UPDATE_USER_DATA,
COULD_NOT_LOAD_USER_DATA_WITH_ID,
COULD_NOT_DELETE_USER_INFORMATION,
COULD_NOT_SAVE_BATCHES_DATA,
COULD_NOT_UPDATE_BATCHES_DATA,
COULD_NOT_LOAD_BATCHES_DATA_WITH_ID,
COULD_NOT_DELETE_BATCHES_INFORMATION,
COULD_NOT_SAVE_GROUP_DATA,
COULD_NOT_UPDATE_GROUP_DATA,
COULD_NOT_LOAD_GROUP_DATA_WITH_ID,
COULD_NOT_DELETE_GROUP_INFORMATION,
MULTIPLE_USERS_FOUND_FOR_USER_NAME,
NO_USER_FOUND_FOR_GIVEN_USER_NAME,
COULD_NOT_LOAD_PAGINATION_DATA,
COULD_NOT_LOAD_REQUIRED_DATA,
UNKNOWN_ERROR,
COULD_NOT_INSERT_AUDIT_LOG_FOR_INSERT_OPERATION,
COULD_NOT_INSERT_AUDIT_LOG_FOR_UPDATE_OPERATION,
COULD_NOT_INSERT_AUDIT_LOG_FOR_DELETE_OPERATION,
COULD_NOT_INSERT_AUDIT_LOG_FOR_LOAD_OPERATION

}
